apiVersion: apps/v1
kind: Deployment

metadata:
  name: housing-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: housing-service

  template:
    metadata:
      labels:
        app: housing-service

    spec:
      containers:
        - name: housing-container
          image: housing-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 3000