apiVersion: v1
kind: Service

metadata:
  name: housing-service

spec:
  type: NodePort

  selector:
    app: housing-service

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007